# Generated by Django 2.2.1 on 2019-05-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HallNews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='HallNew',
        ),
    ]
